// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9LhsKKq9mLC5Nk0HvdcR1kscIMioVxm4',
    appId: '1:674324659963:web:5f2dacc49cacea27bc3a5e',
    messagingSenderId: '674324659963',
    projectId: 'ambataapp-2a984',
    authDomain: 'ambataapp-2a984.firebaseapp.com',
    storageBucket: 'ambataapp-2a984.appspot.com',
    measurementId: 'G-0DN6W9NP82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgWWYvb_hnBi6yl6BCiGhxjMF80L2u1O4',
    appId: '1:674324659963:android:f225abd881c7b217bc3a5e',
    messagingSenderId: '674324659963',
    projectId: 'ambataapp-2a984',
    storageBucket: 'ambataapp-2a984.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLFB03GHYltovP2jvMPfN8becbJsC2pTk',
    appId: '1:674324659963:ios:498de3e2e42e5ad4bc3a5e',
    messagingSenderId: '674324659963',
    projectId: 'ambataapp-2a984',
    storageBucket: 'ambataapp-2a984.appspot.com',
    iosBundleId: 'com.example.projekAmbata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLFB03GHYltovP2jvMPfN8becbJsC2pTk',
    appId: '1:674324659963:ios:c2986887cb8981f0bc3a5e',
    messagingSenderId: '674324659963',
    projectId: 'ambataapp-2a984',
    storageBucket: 'ambataapp-2a984.appspot.com',
    iosBundleId: 'com.example.projekAmbata.RunnerTests',
  );
}
